/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veritabanı;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author mucah
 */
public class Defect extends javax.swing.JFrame {

    Sorgu sorguu = new Sorgu();

    static int dep_deger;
    static int com_deger;
    static String calısan;
    static String baslık;
    static String tanım;
    static int sayi = Sorgu.sorgu.count();
    static String seviye;

    /**
     * Creates new form Defect
     */
    public Defect() {
        initComponents();

        setSize(700, 600);

    }

    public void listele(int d_deger, int c_deger) {

        ArrayList<String> liste = new ArrayList<String>();
        String sorgu = "SELECT kd.kullanici_adi from kullanici_db kd, departman_db dd WHERE kd.dk_id=dd.d_id AND dd.departman=? AND dd.companent=? ";

        try {
            PreparedStatement preparedStatement = sorguu.b.Baglan().prepareStatement(sorgu);
            preparedStatement.setInt(1, d_deger);
            preparedStatement.setInt(2, c_deger);
            ResultSet rs = preparedStatement.executeQuery();

            System.out.println("afdsf");

            while (rs.next()) {

                liste.add(rs.getString("kullanici_adi"));
                System.out.println("liste :" + liste);

            }
            String dizi[] = new String[liste.size()];
            for (int i = 0; i < liste.size(); i++) {
                dizi[i] = liste.get(i);

                // jc_assi.setActionCommand((String) sorguu.listele().get(i));
                System.out.println("boyut :" + liste.size());
                System.out.println("ilk :" + liste.get(i));
            }
            jc_assi.setModel(new DefaultComboBoxModel<>(dizi));

        } catch (SQLException ex) {

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_com = new javax.swing.JLabel();
        jl_grup = new javax.swing.JLabel();
        jl_assi = new javax.swing.JLabel();
        jl_baş = new javax.swing.JLabel();
        jl_tan = new javax.swing.JLabel();
        jc_com = new javax.swing.JComboBox<>();
        jc_grup = new javax.swing.JComboBox<>();
        jc_assi = new javax.swing.JComboBox<>();
        jt_bas = new javax.swing.JTextField();
        jt_tan = new javax.swing.JTextField();
        jb_geri = new javax.swing.JButton();
        jb_olustur = new javax.swing.JButton();
        jl_seviye = new javax.swing.JLabel();
        jc_seviye = new javax.swing.JComboBox<>();
        jl_hata = new javax.swing.JLabel();
        jl_hata2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));

        jl_com.setText("Compenent :");

        jl_grup.setText("Grup :");

        jl_assi.setText("Assignee :");

        jl_baş.setText("Başlık :");

        jl_tan.setText("Tanım :");

        jc_com.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kenan", "Siebel", "Tibco" }));
        jc_com.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_comActionPerformed(evt);
            }
        });

        jc_grup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tester", "Developer", "Operation" }));
        jc_grup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_grupActionPerformed(evt);
            }
        });

        jc_assi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_assiActionPerformed(evt);
            }
        });

        jt_bas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_basActionPerformed(evt);
            }
        });

        jt_tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_tanActionPerformed(evt);
            }
        });

        jb_geri.setText("geri");
        jb_geri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_geriActionPerformed(evt);
            }
        });

        jb_olustur.setText("oluştur");
        jb_olustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_olusturActionPerformed(evt);
            }
        });

        jl_seviye.setText("seviye:");

        jc_seviye.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kritik", "Yüksek", "Normal", "Düsük", " " }));
        jc_seviye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_seviyeActionPerformed(evt);
            }
        });

        jl_hata.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_hata.setForeground(new java.awt.Color(255, 0, 0));

        jl_hata2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_hata2.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jl_com, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(jl_baş, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jl_assi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jl_grup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_bas, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_seviye)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jl_tan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jb_geri)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jc_seviye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jc_com, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jc_grup, javax.swing.GroupLayout.Alignment.LEADING, 0, 240, Short.MAX_VALUE)
                                        .addComponent(jc_assi, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jl_hata2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(93, 93, 93))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jl_hata, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jb_olustur)
                                    .addComponent(jt_tan, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_com, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jc_com, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_grup, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jc_grup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jc_assi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_assi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_baş, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_bas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_tan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_tan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_seviye)
                    .addComponent(jc_seviye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_geri)
                            .addComponent(jb_olustur))
                        .addContainerGap(280, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jl_hata, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_hata2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_geriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_geriActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Giris().setVisible(true);
    }//GEN-LAST:event_jb_geriActionPerformed

    private void jc_comActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_comActionPerformed

        int compenent = jc_com.getSelectedIndex();
        System.out.println("comp" + compenent);
        com_deger = compenent;
    }//GEN-LAST:event_jc_comActionPerformed

    private void jc_grupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_grupActionPerformed

        int grup = jc_grup.getSelectedIndex();
        System.out.println("grup :" + grup);
        dep_deger = grup;
        listele(dep_deger, com_deger);

    }//GEN-LAST:event_jc_grupActionPerformed

    private void jc_assiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_assiActionPerformed

        calısan = (String) jc_assi.getSelectedItem();

        System.out.println("calısan :" + calısan);


    }//GEN-LAST:event_jc_assiActionPerformed


    private void jb_olusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_olusturActionPerformed
        // TODO add your handling code here:
        String durum = "open";
        baslık = jt_bas.getText();
        tanım = jt_tan.getText();

        if (calısan != null && baslık.length() != 0 && tanım.length() != 0) {
            sorguu.mesaj_ekle(baslık, tanım, calısan, durum, (String) jc_seviye.getSelectedItem(), Sorgu.id);
           
            int deger = sorguu.count();
            if (deger > sayi) {
                jl_hata.setText("Defect Oluşturuldu");
                jl_hata2.setText("");
            }

        } else if (calısan == null) {
            jl_hata.setText("Defect Oluşturulamadı");
            jl_hata2.setText("Assignee seçin");

        } else if (baslık.equals("")) {
            jl_hata.setText("Defect Oluşturulamadı");
            jl_hata2.setText("Başlığı doldurun");

        } else if (tanım.equals("")) {
            jl_hata.setText("Defect Oluşturulamadı");
            jl_hata2.setText("Tanımı doldurun");

        }

        seviye = (String) jc_seviye.getSelectedItem();


    }//GEN-LAST:event_jb_olusturActionPerformed

    private void jt_basActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_basActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jt_basActionPerformed

    private void jt_tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_tanActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jt_tanActionPerformed

    private void jc_seviyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_seviyeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jc_seviyeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Defect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Defect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Defect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Defect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Defect().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_geri;
    private javax.swing.JButton jb_olustur;
    private javax.swing.JComboBox<String> jc_assi;
    private javax.swing.JComboBox<String> jc_com;
    private javax.swing.JComboBox<String> jc_grup;
    private javax.swing.JComboBox<String> jc_seviye;
    private javax.swing.JLabel jl_assi;
    private javax.swing.JLabel jl_baş;
    private javax.swing.JLabel jl_com;
    private javax.swing.JLabel jl_grup;
    private javax.swing.JLabel jl_hata;
    private javax.swing.JLabel jl_hata2;
    private javax.swing.JLabel jl_seviye;
    private javax.swing.JLabel jl_tan;
    private javax.swing.JTextField jt_bas;
    private javax.swing.JTextField jt_tan;
    // End of variables declaration//GEN-END:variables

}
