/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veritabanı;

import java.awt.Dimension;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.parser.TokenType;

/**
 *
 * @author mucah
 */
public class Login extends javax.swing.JFrame {

   

    Giris girisss = new Giris();
  
    Baglan baglan = new Baglan();
    Sorgu sorgu = new Sorgu();
    static String mesaj2 = "Bloke oldunuz";
    static String mesaj = " giris hatalı";
    static String kullanici_adii;
    static String parolaa;

    /**
     * Creates new form NewJFrame
     */
    public Login() {
        initComponents();
        setSize(700,600);
         

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jl_k = new javax.swing.JLabel();
        jl_p = new javax.swing.JLabel();
        tf_kullanıcı_adi = new javax.swing.JTextField();
        jl_t = new javax.swing.JLabel();
        giris = new javax.swing.JButton();
        tf_parola = new javax.swing.JPasswordField();
        hata_mesajı = new javax.swing.JLabel();
        blok = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_k.setText("kullanıcı adı :");

        jl_p.setText("parola :");

        jl_t.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jl_t.setText("giriş paneli");

        giris.setText("giris");
        giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisActionPerformed(evt);
            }
        });

        hata_mesajı.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        hata_mesajı.setForeground(new java.awt.Color(255, 0, 51));

        blok.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        blok.setForeground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_t)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_k)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jl_p)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_kullanıcı_adi, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(tf_parola, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(giris))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(blok, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hata_mesajı, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(452, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_t)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_k)
                    .addComponent(tf_kullanıcı_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_p)
                    .addComponent(tf_parola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(giris)
                .addGap(18, 18, 18)
                .addComponent(hata_mesajı, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blok, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(333, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*  public void zamanlayıcı() {

        Timer tmer = new Timer();
        TimerTask task = new TimerTask() {

            int seconds = 3;

            @Override
            public void run() {

                System.out.println("Kalan Zaman:" + seconds--);

                if (seconds < 0) {

                    tmer.cancel();
                    //setVisible(true);
                    new Login().setVisible(true);
                    bloc.setVisible(false);

                }

            }

        };
        tmer.schedule(task, 0, 2000);

    }*/
    public boolean zaman() {
        boolean deger = false;
        if (sorgu.zamanlayıcı(tf_kullanıcı_adi.getText()) >= 2 || sorgu.zamanlayıcı2(tf_kullanıcı_adi.getText()) == null) {
            deger = true;

        }
        return deger;

    }
    private void girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisActionPerformed

        kullanici_adii = tf_kullanıcı_adi.getText();
        parolaa = new String(tf_parola.getPassword());

        if ((sorgu.giris_islem(kullanici_adii, parolaa) && zaman()) == true) {
            setVisible(false);
            girisss.setVisible(true);
            // new Giris().setVisible(true);
            sorgu.basarili_giris(kullanici_adii, 0);
            sorgu.aktif_tarih(kullanici_adii, sorgu.tarih());
            sorgu.blok_tarih_temizle(kullanici_adii, null);

        } else if (sorgu.giris_islem(kullanici_adii, parolaa) == false) {

            sorgu.hatali_giris_ekle(kullanici_adii, (sorgu.hatali_giris_cek(kullanici_adii) + 1));
            hata_mesajı.setText("hatalı giriş" + sorgu.hatali_giris_cek(kullanici_adii));

            if (sorgu.hatali_giris_cek(kullanici_adii) >= 3) {

                blok.setText(mesaj2);
                //setVisible(false);
                //bloc.setVisible(true);
                //zamanlayıcı();

                sorgu.blok_tarih_ekle(kullanici_adii, sorgu.tarih());

            }

        } else if (sorgu.zamanlayıcı(kullanici_adii) < 2) {
            // setVisible(false);
            // bloc.setVisible(true);
            //zamanlayıcı();
            blok.setText(mesaj);

        }


    }//GEN-LAST:event_girisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
     
     

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                
            }
        });
        
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blok;
    private javax.swing.JButton giris;
    private javax.swing.JLabel hata_mesajı;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jl_k;
    private javax.swing.JLabel jl_p;
    private javax.swing.JLabel jl_t;
    private javax.swing.JTextField tf_kullanıcı_adi;
    private javax.swing.JPasswordField tf_parola;
    // End of variables declaration//GEN-END:variables
}
